const menu = [
    {
        key:'HTML',
        name:'HTML',
        icon:`issues-close`,
        path:'/HTML'
    },
    {
        key:'CSS',
        name:'CSS',
        icon:`check-square`,
        path:'/CSS',
        children:[
            {
                key:'LESS',
                name:'LESS',
                icon:`check-square`,
                path:'/LESS'
            },
            {
                key:'SASS',
                name:'SASS',
                icon:`check-square`,
                path:'/SASS'
            },
            {
                key:'Stylus',
                name:'Stylus',
                icon:`check-square`,
                path:'/Stylus'
            },
        ]
    },
    {
        key:'JavaScript',
        name:'JavaScript',
        icon:`edit`,
        path:'/JavaScript'
    },
    {
        key:'Graphics',
        name:'Graphics',
        icon:`highlight`,
        path:'/Graphics'
    },
    {
        key:'HTTP',
        name:'HTTP',
        icon:`strikethrough`,
        path:'/HTTP'
    },
    {
        key:'API',
        name:'API',
        icon:`radius-setting`,
        path:'/API'
    }
]

export default menu;